
{{- if .Values.webui.ingress.enabled -}}
{{- $fullName := include "webui.fullname" . -}}
{{- $svcPort := .Values.webui.service.port -}}
{{- $endpoint := .Values.endpoint -}}
{{- $subdomain := .Values.webui_subdomain -}}
{{- if and .Values.webui.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.webui.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.webui.ingress.annotations "kubernetes.io/ingress.class" .Values.webui.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "webui.labels" . | nindent 4 }}
  {{- with .Values.webui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.webui.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.webui.ingress.className }}
  {{- end }}
  {{- if .Values.webui.ingress.tls }}
  tls:
    {{- range .Values.webui.ingress.tls }}
    - hosts:
        - {{ $subdomain }}.{{ $endpoint }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.webui.ingress.hosts }}
    - host: {{ $subdomain }}.{{ $endpoint }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: webui
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: webui
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}