---
apiVersion: v1
kind: Service
metadata:
  name: webui
  labels:
    {{- include "webui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webui.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "webui.selectorLabels" . | nindent 4 }}