{{- if .Values.emshelpcenter.enabled }}
{{- if eq (include "platform" .) "aws" }}
{{- $reg := .Values.emshelpcenter.registryCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: github-token
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,failed,before-hook-creation
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" $reg.registry $reg.username $reg.password (printf "%s:%s" $reg.username $reg.password | b64enc) | b64enc | quote }}
{{- end }}
{{- end }}
