{{- if .Values.eventcollector.kafkaCluster.enabled }}
{{- if .Values.eventcollector.config }}
---
apiVersion: v1
data:
  application.properties: |+
    {{- .Values.eventcollector.config | nindent 4 }}
    {{- with .Values.spc_support }}
    SPC_SERIAL_NUMBER={{.serial_number}}
    {{- end }}
kind: ConfigMap
metadata:
  name: {{ template "eventcollector.fullname" . }}-config
{{- end }}
{{- if .Values.eventcollector.env }}
---
apiVersion: v1
data:
    {{- with .Values.eventcollector.env }}
    {{- toYaml . | nindent 2 }}
    {{- end }}
kind: ConfigMap
metadata:
  name: {{ template "eventcollector.fullname" . }}-env
{{- end }}
---
apiVersion: v1
data:
  log4j2.properties: |+
    # Set to debug or trace if log4j initialization is failing
    status = error
    monitorInterval=60

    # Name of the configuration
    name = ConsoleLogConfig

    # Console appender configuration
    appender.console.type = Console
    appender.console.name = LogToConsole
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = %d{MM/dd HH:mm:ss,SSS} %highlight{%level}{FATAL=bg_red,ERROR=red, WARN=yellow, INFO=green, DEBUG=blue, TRACE=white} [%-15.15t] %c{4} [%4L]: %m%n

    rootLogger.level = INFO
    rootLogger.appenderRefs = stdout
    rootLogger.appenderRef.stdout.ref = LogToConsole

    logger.netty.name = io.netty
    logger.netty.level = INFO

    logger.sshd.name = org.apache.sshd
    logger.sshd.level = INFO

    logger.netconf.name= org.broadband_forum.obbaa.netconf
    logger.netconf.level = INFO

    logger.netconfapiclient.name= org.broadband_forum.obbaa.netconf.api.client
    logger.netconfapiclient.level= INFO

    logger.netconfapicodec.name = org.broadband_forum.obbaa.netconf.api.codec.v2
    logger.netconfapicodec.level = INFO

    logger.ems.name = ems.platform
    logger.ems.level = DEBUG

    logger.emsCPE.name = ems.ems.collector.cpe
    logger.emsCPE.level = WARN

    logger.emsENB.name = ems.ems.collector.enb
    logger.emsENB.level = WARN

    logger.emsES.name = ems.ems.collector.cpe.AcsElkSender
    logger.emsES.level = TRACE

    logger.emsSmallCell.name = ems.ems.collector.smallcell
    logger.emsSmallCell.level= TRACE

    logger.emsSmallCellFM.name = ems.ems.collector.smallcell.fm
    logger.emsSmallCellFM.level = TRACE

    logger.emsSmallCellPM.name = ems.ems.collector.smallcell.pm
    logger.emsSmallCellPM.level= TRACE

    logger.emsTOC.name = ems.ems.collector.toc
    logger.emsTOC.level = TRACE

    logger.emsSPC.name = ems.ems.collector.spc
    logger.emsSPC.level= TRACE

    logger.emsDisc.name = ems.ems.discovery
    logger.emsDisc.level = WARN

    logger.emsEvents.name = ems.ems.eventstream
    logger.emsEvents.level = TRACE
kind: ConfigMap
metadata:
  name: {{ template "eventcollector.fullname" . }}-log-config
---
{{- end }}