platform: onprem
enabled: true
ConnectionUrls:
  mongo:
    uri: "mongodb://mongo-tenant:27017/?serverSelectionTimeoutMS=4000&replicaSet=rs0"
initContainers:
  mongoImage:
    repo: public.ecr.aws/bitnami/mongodb
    tag: 8.0.12-debian-12-r0
