apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sftp-server.fullname" . }}-users
data:
  users.conf: |
      {{- range $user := .Values.sftp.sftpConfig.users }}
      {{- if eq $user.encrypted true }}
      {{ $user.username }}:{{ $user.password }}:e:{{ $user.uid}}:{{ $user.gid }}:{{ $user.dir }}
      {{- else }}
      {{ $user.username }}:{{ $user.password }}:{{ $user.uid}}:{{ $user.gid }}:{{ $user.dir }}
      {{- end }}
      {{- end }}