{{- if and .Values.ngf.smallcell_support.enabled .Values.ngf.ngf_enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ems-certs-mgmt
spec:
  parentRefs:
  - name: ems
  hostnames:
    - {{ include "ngf.hostname" . }}
  rules:
  - matches:
    {{- range .Values.ngf.paths.emscertmanager }}
    - path:
        type: PathPrefix
        value: {{ . }}
    {{- end }}
    filters:
    - type: ExtensionRef
      extensionRef:
        group: gateway.nginx.org
        kind: SnippetsFilter
        name: oauth2
    backendRefs:
    - name: ems-certs-mgmt-headless
      port: 7702
{{- end }}