{{- if and .Values.ngf.smallcell_support.enabled .Values.ngf.ngf_enabled }}
apiVersion: gateway.nginx.org/v1alpha1
kind: SnippetsFilter
metadata:
  name: oauth2
spec:
  snippets:
    - context: http.server.location
      value: |
        add_header "Access-Control-Allow-Origin" "https://{{ include "ngf.allowOrigin" . }}" always;
        add_header "Access-Control-Allow-Methods" "GET, POST, OPTIONS, PUT, DELETE" always;
        add_header "Access-Control-Allow-Headers" "Authorization, Content-Type, Accept, Origin, User-Agent" always;
        add_header "Access-Control-Allow-Credentials" "true" always;
        if ($request_method = OPTIONS) {
          return 204;
        }
        auth_request "/oauth2/auth";
{{- end }}