{{- if .Values.elasticsearch.ingress.enabled -}}
{{- $fullName := include "elasticsearch.fullname" . -}}
{{- $svcPort := .Values.elasticsearch.service.http.port -}}
{{- $endpoint := .Values.endpoint -}}

{{- if and .Values.elasticsearch.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.elasticsearch.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.elasticsearch.ingress.annotations "kubernetes.io/ingress.class" .Values.elasticsearch.ingress.className }}
  {{- end }}
{{- end }}

{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "elasticsearch.labels" . | nindent 4 }}
  {{- with .Values.elasticsearch.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.elasticsearch.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.elasticsearch.ingress.className }}
  {{- end }}

{{- if and (eq (include "platform" .) "onprem") .Values.elasticsearch.ingress.tls }}
  tls:
    {{- range .Values.elasticsearch.ingress.tls }}
    - hosts:
        - elastic.{{ $endpoint }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}

  rules:
    {{- range .Values.elasticsearch.ingress.hosts }}
    - host: elastic.{{ $endpoint }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: elastic
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: elastic
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
