apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kibana
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kibana.selectorLabels" . | nindent 8 }}
  serviceName: kibana
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "kibana.selectorLabels" . | nindent 8 }}
    spec:
      {{- if eq (include "platform" .) "aws" }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      {{- with .Values.kibana.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq (include "platform" .) "aws" }}
      {{- with .Values.kibana.nodeSelector.aws }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else if eq (include "platform" .) "onprem" }}
      {{- with .Values.kibana.nodeSelector.onprem }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      {{- with .Values.kibana.nodeSelector.default }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.kibana.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq (include "platform" .) "onprem" }}
      {{- with .Values.kibana.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      initContainers:
        - name: wait-for-dependency
          image: {{ .Values.curlImage.repo | default "curlimages/curl" }}:{{ .Values.curlImage.tag | default "8.12.1" }}
          command: [ "/bin/sh", "-c" ]
          env:
            - name: ELK_USERNAME
              valueFrom:
                secretKeyRef:
                  {{- if eq (include "platform" .) "aws" }}
                  name: elastic-admin-client
                  {{- else }}
                  name: internal-elastic-admin-client
                  {{- end }}
                  key: elk-username
            - name: ELK_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if eq (include "platform" .) "aws" }}
                  name: elastic-admin-client
                  {{- else }}
                  name: internal-elastic-admin-client
                  {{- end }}
                  key: elk-password
          args:
            [
                    "while [[ $(curl -sw '%{http_code}' -u \"$ELK_USERNAME:$ELK_PASSWORD\" {{ .Values.ConnectionUrls.elastic }} -o /dev/null) -ne 200 ]]; do sleep 5; echo 'Waiting for the Elastic to be ready...'; done; echo 'Connection with Elastic established'",
            ]
      priorityClassName: ems-platform-low-priority
      containers:
        - env:
            - name: ELASTICSEARCH_HOSTS
              valueFrom:
                configMapKeyRef:
                  key: ELASTICSEARCH_HOSTS
                  name: kibana-elastic-host-env
            - name: ELASTIC_HOST
              valueFrom:
                configMapKeyRef:
                  key: ELASTIC_HOST
                  name: kibana-elastic-host-env
            - name: ELASTIC_PORT
              valueFrom:
                configMapKeyRef:
                  key: ELASTIC_PORT
                  name: kibana-elastic-host-env
            - name: ELASTIC_URL
              valueFrom:
                configMapKeyRef:
                  key: ELASTIC_URL
                  name: kibana-elastic-host-env
            {{- if eq (include "platform" .) "aws" }}
            - name: WAITFORIT_HOST
              valueFrom:
                configMapKeyRef:
                  key: WAITFORIT_HOST
                  name: kibana-elastic-host-env
            - name: WAITFORIT_PORT
              valueFrom:
                configMapKeyRef:
                  key: WAITFORIT_PORT
                  name: kibana-elastic-host-env
            - name: WAITFORIT_URL
              valueFrom:
                configMapKeyRef:
                  key: WAITFORIT_URL
                  name: kibana-elastic-host-env
            {{- end }}
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  {{- if eq (include "platform" .) "aws" }}
                  name: elastic-admin-client
                  {{- else }}
                  name: internal-elastic-admin-client
                  {{- end }}
                  key: elk-username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if eq (include "platform" .) "aws" }}
                  name: elastic-admin-client
                  {{- else }}
                  name: internal-elastic-admin-client
                  {{- end }}
                  key: elk-password
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  {{- if eq (include "platform" .) "aws" }}
                  name: elastic-admin-client
                  {{- else }}
                  name: internal-elastic-admin-client
                  {{- end }}
                  key: elk-username
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if eq (include "platform" .) "aws" }}
                  name: elastic-admin-client
                  {{- else }}
                  name: internal-elastic-admin-client
                  {{- end }}
                  key: elk-password
          image: "{{ .Values.kibana.image }}:{{ .Values.kibana.tag }}"
          imagePullPolicy: {{ .Values.kibana.pullPolicy }}
          startupProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 30
            tcpSocket:
              host:
              port: 5601
          readinessProbe:
            tcpSocket:
              port: 5601
            failureThreshold: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5601
            failureThreshold: 3
            periodSeconds: 10         
          name: kibana
          resources:
            {{- toYaml .Values.kibana.resources | nindent 12 }}
          ports:
            - containerPort: 5601
              name: http
          resources: {}
          volumeMounts:
            - name: elastic-admin-client-secrets
              mountPath: "/opt/ems-platform/config/elastic"
              readOnly: true
      restartPolicy: Always
      volumes:
          - name: elastic-admin-client-secrets
            {{- if eq (include "platform" .) "aws" }}
            csi:
              driver: secrets-store.csi.k8s.io
              readOnly: true
              volumeAttributes:
                secretProviderClass: "{{ .Values.kibana.secrets.internal_elastic_admin_client | replace "_" "-" }}"
            {{- else }}
            secret:
              secretName: internal-elastic-admin-client
            {{- end }}
  {{- if eq (include "platform" .) "aws" }}
  # volumeClaimTemplates:
  #   - metadata:
  #       name: kibana-persistent-storage
  #     spec:
  #       accessModes:
  #         - ReadWriteOnce
  #       resources:
  #         requests:
  #           storage: 5Gi
  {{- end }}