{{- if .Values.tus.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tus-kafka-proxy-application-config
  labels:
    {{- include "tus.labels" . | nindent 4 }}
    app: tus-kafka-proxy
data:
  application.yaml: |
    app:
      name: "tus-kafka-proxy"
      devMode: {{ .Values.dev_mode | default true }}

    server:
      port: "8080"

    kafka:
      kafkaBootstrapServers:
        - "ems-platform-kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
      connectionTimeout: 10000
      topic: "ems-platform-tus-file-uploaded"
      notificationTopic: "ems-platform-tus-file-uploaded-notification"

    logger:
      logLevel: "INFO"
      callerLevel: "INFO"
      stackTraceLevel: "ERROR"
      charLimit: 1024
      formatJson: true

    auth:
      enabled: true

    fiber:
      bodyLimit: 200 # in MB
{{- end }}
