{{- if .Values.cpeSupport.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: genieacsfs
  labels:
    {{- include "genieacsfs.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "genieacsfs.selectorLabels" . | nindent 6 }}
  serviceName: genieacsfs
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "genieacsfs.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      initContainers:
      - name: wait-for-dependency
        image: {{ .Values.initContainers.busyboxImage.repo | default "busybox" }}:{{ .Values.initContainers.busyboxImage.tag | default "1.36.0" }}
        command: ['sh', '-c', 'until nslookup mongo | grep "Name:"; do echo waiting for mongo; sleep 2; done;']
      priorityClassName: ems-platform-medium-priority
      containers:
        - name: genieacsfs
          image: "{{ .Values.image }}:{{ .Values.tag }}"
          ports:
            - containerPort: 7567
              name: fs
          imagePullPolicy: {{ .Values.pullPolicy }}
          startupProbe:
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 30
            tcpSocket:
              host:
              port: 7567
          readinessProbe:
            tcpSocket:
              port: 7567
            failureThreshold: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 7567
            failureThreshold: 8
            periodSeconds: 10
          envFrom:
            - configMapRef:
                name: genieacs-config-env
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: genieacs-fs-persistent-storage
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
# dummy volume for storing secrets
{{- end }}