{{- if and (include "coreApi.rbacEnabled" . | eq "true") (eq (include "coreApi.platform" .) "aws") }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "coreApi.serviceAccountName" . }}
  namespace: {{ template "coreApi.namespace" . }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "coreApi.roleName" . }}
  namespace: {{ template "coreApi.namespace" . }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "coreApi.roleBindingName" . }}
  namespace: {{ template "coreApi.namespace" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "coreApi.serviceAccountName" . }}
    namespace: {{ template "coreApi.namespace" . }}
roleRef:
  kind: Role
  name: {{ template "coreApi.roleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}