---
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if eq (include "platform" .) "onprem" }}
  name: toc-sa
  {{- else if eq (include "platform" .) "aws" }}
  name: ems-platform-toc-sa
  {{- end }}
  namespace: ems-platform
  {{- if eq (include "platform" .) "aws" }}
  annotations:
    eks.amazonaws.com/role-arn: "{{ index .Values.toc "ems-platform_toc_access_role" }}"
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: toc-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: [ "" ]
    resources: [ "*" ]
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: toc-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    {{- if eq (include "platform" .) "onprem" }}
    name: toc-sa
    {{- else if eq (include "platform" .) "aws" }}
    name: ems-platform-toc-sa
    {{- end }}
    namespace: ems-platform