{{- if .Values.cpeSupport.enabled }}
{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: genieacscwmp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: genieacscwmp
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  metrics:
    {{- if .Values.hpa.averageCpuUtilization }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.averageCpuUtilization }}
    {{- end }}
    {{- if .Values.hpa.averageMemoryUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.averageMemoryUtilization }}
    {{- end }}
{{- end }}
{{- end }}