{{- if eq .Values.platform "aws" }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Values.secrets.internal_elastic_admin_client | replace "_" "-" }}"
  namespace: ems-platform
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.internal_elastic_admin_client }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: '"elk-username"'
            objectAlias: 'elk-username'
          - path: '"elk-password"'
            objectAlias: 'elk-password'

  secretObjects:
    - secretName: elastic-admin-client
      type: Opaque
      labels:
        app: elastic
      annotations:
        kubernetes.io/service-account.name: "default"
      data:
        - objectName: elk-username
          key: elk-username
        - objectName: elk-password
          key: elk-password
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Values.secrets.internal_elastic_client | replace "_" "-" }}"
  namespace: ems-platform
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.internal_elastic_client }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: '"elk-username"'
            objectAlias: 'elk-username'
          - path: '"elk-password"'
            objectAlias: 'elk-password'

  secretObjects:
    - secretName: elastic-client
      type: Opaque
      labels:
        app: elastic
      annotations:
        kubernetes.io/service-account.name: "default"
      data:
        - objectName: elk-username
          key: elk-username
        - objectName: elk-password
          key: elk-password

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Values.secrets.internal_keycloak_toc_client | replace "_" "-" }}"
  namespace: ems-platform
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.internal_keycloak_toc_client }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: '"keycloak-id"'
            objectAlias: 'keycloak-id'
          - path: '"keycloak-secret"'
            objectAlias: 'keycloak-secret'

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Values.secrets.internal_keycloak_core_api_client | replace "_" "-" }}"
  namespace: ems-platform
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.internal_keycloak_core_api_client }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: '"keycloak-id"'
            objectAlias: 'keycloak-id'
          - path: '"keycloak-secret"'
            objectAlias: 'keycloak-secret'

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Values.secrets.external_keycloak_admin_client | replace "_" "-" }}"
  namespace: ems-platform
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.external_keycloak_admin_client }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: '"keycloak-username"'
            objectAlias: 'keycloak-username'
          - path: '"keycloak-password"'
            objectAlias: 'keycloak-password'

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Values.secrets.external_rds_keycloak_client | replace "_" "-" }}"
  namespace: ems-platform
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.external_rds_keycloak_client }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: '"pg-username"'
            objectAlias: 'pg-username'
          - path: '"pg-password"'
            objectAlias: 'pg-password'

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Values.secrets.internal_gh_ctd_repo_client| replace "_" "-" }}"
  namespace: ems-platform
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.internal_gh_ctd_repo_client }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: '"gh-token"'
            objectAlias: 'gh-token'
          - path: '"gh-username"'
            objectAlias: 'gh-username'

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Values.secrets.internal_gh_sw_image_repo_client | replace "_" "-" }}"
  namespace: ems-platform
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.internal_gh_sw_image_repo_client }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: '"gh-token"'
            objectAlias: 'gh-token'
          - path: '"gh-username"'
            objectAlias: 'gh-username'

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Values.secrets.internal_gh_help_center_repo_client | replace "_" "-" }}"
  namespace: ems-platform
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.internal_gh_help_center_repo_client }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: '"gh-username"'
            objectAlias: 'gh-username'
          - path: '"gh-token"'
            objectAlias: 'gh-token'

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Values.secrets.internal_genieacs | replace "_" "-" }}"
  namespace: ems-platform
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.internal_genieacs }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: '"genieacs-ui-init-secret"'
            objectAlias: 'genieacs-ui-init-secret'

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Values.secrets.external_smtp_default_user_client | replace "_" "-" }}"
  namespace: ems-platform
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.external_smtp_default_user_client }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: '"smtp-username"'
            objectAlias: 'smtp-username'
          - path: '"smtp-password"'
            objectAlias: 'smtp-password'

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Values.secrets.identity }}"
  namespace: ems-platform
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.internal_spark_identity_secret }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: '"chain.crt"'
            objectAlias: 'chain.crt'
          - path: '"privateKeyPassword"'
            objectAlias: 'privateKeyPassword'
          - path: '"tls.crt"'
            objectAlias: 'tls.crt'
          - path: '"tls.key"'
            objectAlias: 'tls.key'

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Values.secrets.trust }}"
  namespace: ems-platform
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.internal_spark_trust_secret }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: '"ca.crt"'
            objectAlias: 'ca.crt'

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Values.secrets.external_ems_aoa_client | replace "_" "-" }}"
  namespace: ems-platform
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.external_ems_aoa_client }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: '"ems-username"'
            objectAlias: 'ems-username'
          - path: '"ems-password"'
            objectAlias: 'ems-password'

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mongoatlas-admin-secrets
  namespace: ems-platform
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.external_mongo_admin_secret }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: '"mongo-username"'
            objectAlias: 'mongo-username'
          - path: '"mongo-password"'
            objectAlias: 'mongo-password'

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mongoatlas-emsdb-secrets
  namespace: ems-platform
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.external_mongo_emsdb_secret }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: '"mongo-username"'
            objectAlias: 'mongo-username'
          - path: '"mongo-password"'
            objectAlias: 'mongo-password'

  secretObjects:
    - secretName: mongo-emsdb-client
      type: Opaque
      labels:
        app: mongo
      annotations:
        kubernetes.io/service-account.name: "default"
      data:
        - objectName: mongo-username
          key: mongo-username
        - objectName: mongo-password
          key: mongo-password

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: "{{ .Values.secrets.internal_pg_client | replace "_" "-" }}"
  namespace: ems-platform
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "{{ .Values.secrets.internal_pg_client }}"
        objectType: "secretsmanager"
        jmesPath:
          - path: '"pg-ems-platform-perms-client-username"'
            objectAlias: 'pg-ems-platform-perms-client-username'
          - path: '"pg-ems-platform-perms-client-password"'
            objectAlias: 'pg-ems-platform-perms-client-password'

---
{{- end }}