apiVersion: v1
kind: Secret
metadata:
  name: cts-repo-secret
type: Opaque
data:
  CTS_REPO_REPONAME: {{ .Values.cts.repo.name | b64enc | quote }}
  CTS_REPO_GITHUBUSER: {{ .Values.cts.repo.user | b64enc | quote }}
  CTS_REPO_GITHUBTOKEN: {{ .Values.cts.repo.token | b64enc | quote }}
