{{- if .Values.cts.smallcell_support.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cts
  labels:
    {{- include "cts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.cts.replicaCount }}
  selector:
    matchLabels:
      {{- include "cts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cts.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
      serviceAccountName: {{ .Values.cts.serviceAccountName }}
      {{- with .Values.cts.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      priorityClassName: ems-platform-high-priority
      initContainers:
      - name: wait-for-dependency
        image: {{ .Values.cts.initContainers.mongoImage.repo | default "public.ecr.aws/bitnami/mongodb" }}:{{ .Values.cts.initContainers.mongoImage.tag | default "8.0.6-debian-12-r0" }}
        env:
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                {{- if eq (include "platform" .) "onprem" }}
                name: external-mongo-emsdb-secret
                {{- else if eq (include "platform" .) "aws" }}
                name: mongo-emsdb-client
                {{- end }}
                key: mongo-username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                {{- if eq (include "platform" .) "onprem" }}
                name: external-mongo-emsdb-secret
                {{- else if eq (include "platform" .) "aws" }}
                name: mongo-emsdb-client
                {{- end }}
                key: mongo-password
        command:
          - bash
          - -c
          - >
            {{- if eq (include "platform" .) "aws" }}
            until mongosh "{{ .Values.cts.ConnectionUrls.mongo.aws.uri }}" --eval "quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)";
            {{- else if eq (include "platform" .) "onprem" }}
            until mongosh "{{ .Values.cts.ConnectionUrls.mongo.onprem.uri }}" --eval "quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)";
            {{- end }}
            do echo "Waiting for MongoDB to be available"; sleep 2; done;

      - name: wait-for-toc
        image: {{ .Values.cts.initContainers.curlImage.repo | default "curlimages/curl" }}:{{ .Values.cts.initContainers.curlImage.tag | default "8.12.1" }}
        command: [ "/bin/sh", "-c" ]
        args:
          - "while [[ $(curl -sIw '%{http_code}' http://toc-headless:7001/health -o /dev/null) -ne 200 ]]; do sleep 5; echo 'Waiting for the toc to be ready...'; done; echo 'Connection with toc established'"
      containers:
        - image: "{{ .Values.cts.image }}:{{ .Values.cts.tag }}"
          imagePullPolicy: {{ .Values.cts.pullPolicy }}
          name: cts
          env:
            - name: CTS_REPO_REPONAME
              valueFrom:
                secretKeyRef:
                  name: cts-repo-secret
                  key: CTS_REPO_REPONAME
            - name: CTS_REPO_GITHUBUSER
              valueFrom:
                secretKeyRef:
                  name: cts-repo-secret
                  key: CTS_REPO_GITHUBUSER
            - name: CTS_REPO_GITHUBTOKEN
              valueFrom:
                secretKeyRef:
                  name: cts-repo-secret
                  key: CTS_REPO_GITHUBTOKEN
          ports:
            - containerPort: 7701
              name: http
          resources:
            {{- toYaml .Values.cts.resources | nindent 12 }}
          volumeMounts:
            - name: cts-application-config
              mountPath: /app/config/application.yaml
              subPath: application.yaml
          {{- if eq (include "platform" .) "aws" }}
            - name: gh-secrets-ctd
              mountPath: "/opt/ems-platform/config/github"
              readOnly: true
          {{- end }}
            - name: mongo-emsdb-secrets
              mountPath: "/opt/ems-platform/config/mongo"
              readOnly: true
            - name: keycloak-toc-secrets
              mountPath: "/opt/ems-platform/config/keycloak"
              readOnly: true
            - name: elastic-client-secrets
              mountPath: "/opt/ems-platform/config/elastic"
              readOnly: true
            - name: pg-perms-ems-platform-secrets
              mountPath: "/opt/ems-platform/config/postgres"
              readOnly: true
            {{- end }}
      restartPolicy: Always
      {{- if eq (include "platform" .) "aws" }}
      {{- with .Values.cts.nodeSelector.aws }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else if eq (include "platform" .) "onprem" }}
      {{- with .Values.cts.nodeSelector.onprem }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      {{- with .Values.cts.nodeSelector.default }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.cts.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.cts.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: cts-application-config
          configMap:
            name: cts-application-config
        {{- if eq (include "platform" .) "onprem" }}
        - name: pg-perms-ems-platform-secrets
          secret:
            secretName: internal-pg-client
        - name: mongo-emsdb-secrets
          secret:
            secretName: external-mongo-emsdb-secret
        - name: elastic-client-secrets
          secret:
            secretName: internal-elastic-admin-client
        - name: keycloak-toc-secrets
          secret:
            secretName: internal-keycloak-toc-client
        {{- else if eq (include "platform" .) "aws" }}
        - name: gh-secrets-ctd
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "{{ .Values.cts.secrets.internal_gh_ctd_repo_client | replace "_" "-" }}"
        - name: pg-perms-ems-platform-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "{{ .Values.cts.secrets.internal_pg_client | replace "_" "-" }}"
        - name: mongo-emsdb-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: mongoatlas-emsdb-secrets
        - name: elastic-client-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "{{ .Values.cts.secrets.internal_elastic_client | replace "_" "-" }}"
        - name: keycloak-toc-secrets
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "{{ .Values.cts.secrets.internal_keycloak_toc_client | replace "_" "-" }}"
{{- end }}