platform: onprem
cpeSupport:
  enabled: true
loadBalancerIP: "0.0.0.0"
image: ghcr.io/vlad-radu-anca/genieacs-cwmp
tag: latest
pullPolicy: Always
replicaCount: 1
imagePullSecrets: []
podAnnotations: {}
tolerations: []
resources: {}
nodeSelector:
  onprem: {}
  aws: {}
affinity: {}
worker_processes: 1
service:
  type: ClusterIP
  port: 7547
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  averageCpuUtilization: 80
  averageMemoryUtilization: 80
initContainers:
  busyboxImage:
    repo: busybox
    tag: 1.36.1

securityContext:
  fsGroup: 2000
  runAsUser: 2500
  runAsGroup: 2500
