{{- if eq .Values.platform "aws" }}
{{- $reg := .Values.emsui.registryCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" $reg.registry $reg.username $reg.password (printf "%s:%s" $reg.username $reg.password | b64enc) | b64enc | quote }}
{{- end }}
